name: Build and deploy the Frontend to Azure Web App

on:
  push:
    branches:
      - main  
  workflow_dispatch:

env:
  APPLICATION_PUBLISH_PROFILE: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
  WEBAPP_NAME: "okapi-ia"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v4
        with:
          node-version: "20.x"
        #   cache: "npm"

      - name: Install dependencies and build
        run: |
          npm install
          npm run build
        working-directory: ./frontend
      
      - name: List build output
        run: find ./.next -type d
        working-directory: ./frontend
      

#       - name: Copy static files
#         run: |
#           mkdir -p ./.next/standalone/.next
#           cp -R ./.next/static ./.next/standalone/.next/static
#         working-directory: ./frontend

#       - name: Upload artifact for deployment job
#         uses: actions/upload-artifact@v4
#         with:
#           name: app
#           path: ./.next/standalone

#   deploy:
#     runs-on: ubuntu-latest
#     needs: build
#     steps:
#       - name: Download artifact from build job
#         uses: actions/download-artifact@v4
#         with:
#           name: app

#       - name: "Deploy to Azure Web App"
#         uses: azure/webapps-deploy@v3
#         with:
#           app-name: ${{ env.WEBAPP_NAME }}
#           slot-name: "Production"
#           publish-profile: ${{ env.APPLICATION_PUBLISH_PROFILE }}
#           package: ./.next/standalone
